"use client"

import React, { createContext, useContext, useState, useEffect } from "react"

type Language = "ko" | "en"

interface LanguageContextType {
  language: Language
  setLanguage: (lang: Language) => void
  t: (key: string) => string
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined)

// Translation dictionary
const translations: Record<Language, Record<string, string>> = {
  ko: {
    // Header
    "header.season": "Season 2",
    "header.openSource": "Open Source",
    "header.tooltip.openSource": "AI 기반 주식 분석 및 매매 시스템 • MIT License",
    "header.startDate": "시작: 2025.09.29",
    "header.updated": "업데이트",
    "header.realtimeUpdate": "실시간 업데이트",
    "header.dashboard": "대시보드",
    "header.aiDecisions": "AI 보유 분석",
    "header.trading": "거래 내역",
    "header.watchlist": "관심 종목",
    "header.tooltip.github": "GitHub 저장소",
    "header.tooltip.telegram": "텔레그램 채널",
    "header.tooltip.theme": "테마 전환",

    // Loading
    "loading.text": "데이터 로딩 중...",

    // Tables
    "table.realPortfolio": "실전투자 포트폴리오",
    "table.simulator": "프리즘 시뮬레이터",
    "table.stock": "종목",
    "table.stockName": "종목명",
    "table.sector": "섹터",
    "table.quantity": "수량",
    "table.avgPrice": "평균단가",
    "table.currentPrice": "현재가",
    "table.buyPrice": "매수가",
    "table.targetPrice": "목표가",
    "table.stopLoss": "손절가",
    "table.profitRate": "수익률",
    "table.profitAmount": "평가손익",
    "table.totalValue": "평가금액",
    "table.holdingDays": "보유일",
    "table.period": "기간",
    "table.weight": "비중",
    "table.unknown": "알 수 없음",

    // Metrics Cards - Real Trading
    "metrics.realTrading": "실전투자 (Season 2)",
    "metrics.realTotalAssets": "실전 총 자산",
    "metrics.realHoldingsProfit": "실전 보유종목 평가손익",
    "metrics.realProfitDist": "실전 포트폴리오 손익 분포",
    "metrics.startAmount": "시작금액",
    "metrics.deposit": "예수금",
    "metrics.stocks": "개 종목",
    "metrics.assetsDesc": "평가금액 + 예수금",
    "metrics.holdingsProfitDesc": "현재 보유중인 종목의 손익",
    "metrics.excludeRealized": "실현손익 제외",
    "metrics.profitDistDesc": "현재 보유 종목 수익/손실 현황",
    "metrics.fullyInvested": "전액 투자중",
    "metrics.wins": "승",
    "metrics.losses": "패",
    "metrics.breakEven": "보합",
    "metrics.totalStocks": "총",
    "metrics.winRate": "승률",

    // Metrics Cards - Simulator
    "metrics.simulator": "프리즘 시뮬레이터",
    "metrics.simSoldProfit": "시뮬레이터 매도종목 누적수익률",
    "metrics.simAvgHoldingDays": "시뮬레이터 평균 보유기간",
    "metrics.simCurrentProfit": "시뮬레이터 보유종목 누적수익률",
    "metrics.waitingSell": "매도 대기중",
    "metrics.onlyHolding": "현재 보유만 존재",
    "metrics.updateOnSell": "매도 시 업데이트",
    "metrics.soldProfitDesc": "매도 완료한 종목 수익률 합계",
    "metrics.sold": "매도",
    "metrics.soldBasis": "건 매도 기준",
    "metrics.needStrategy": "보유 전략 확인 필요",
    "metrics.avgHoldingDesc": "매도까지 평균 소요 기간",
    "metrics.holding": "보유",
    "metrics.avgProfit": "평균",
    "metrics.slotUsage": "슬롯 사용률",
    "metrics.currentProfitDesc": "현재 보유 종목 수익률 합계",
    "metrics.started": "시작",
    "metrics.elapsed": "일 경과",

    // Operating Costs
    "costs.title": "프로젝트 운영 비용 투명 공개",
    "costs.description": "오픈소스 프로젝트의 지속 가능한 운영을 위해 전월 비용을 공개합니다",
    "costs.serverHosting": "서버 호스팅",
    "costs.basis": "기준",
    "costs.perMonth": "/ 월",
    "costs.year": "년",
    "costs.month": "월",
    "costs.helpQuestion": "이 프로젝트가 도움이 되셨나요?",
    "costs.sponsorDesc": "GitHub Sponsor를 통해 프로젝트의 지속 가능한 개발을 지원해주세요",
    "costs.becomeSponsor": "스폰서 되기",

    // Badges
    "badge.realTrading": "실전투자",
    "badge.aiSimulation": "AI 시뮬레이션",
    "badge.season2": "Season 2",
    "badge.koreanInvestment": "한국투자증권",

    // Date/Time
    "date.year": "년",
    "date.month": "월",
    "date.day": "일",

    // Common
    "common.won": "원",
    "common.krw": "₩",
    "common.percent": "%",
    "common.days": "일",
    "common.trades": "건",
    "common.shares": "주",
    "common.other": "기타",
    "common.unclassified": "미분류",
    "metrics.totalReturn": "누적 수익률",
    "metrics.avgReturn": "평균 수익률",
    "metrics.avgHoldingDays": "평균 보유일",
    "metrics.totalTrades": "총 거래",

    // Charts
    "chart.prismReturn": "프리즘 시뮬레이터 (누적 실현)",
    "chart.returnComparisonKospi": "수익률 비교 (KOSPI 기준)",
    "chart.returnComparisonKosdaq": "수익률 비교 (KOSDAQ 기준)",

    // Stock Detail Modal
    "modal.stockDetail": "종목 상세",
    "modal.close": "닫기",
    "modal.currentPrice": "현재가",
    "modal.profitRate": "수익률",
    "modal.holdingInfo": "보유 정보",
    "modal.holdingQuantity": "보유 수량",
    "modal.avgBuyPrice": "평균 매입가",
    "modal.evaluationAmount": "평가 금액",
    "modal.evaluationPL": "평가 손익",
    "modal.portfolioWeight": "포트폴리오 비중",
    "modal.tradingInfo": "매매 정보",
    "modal.buyDate": "매수일",
    "modal.buyPrice": "매수가",
    "modal.targetPrice": "목표가",
    "modal.stopLossPrice": "손절가",
    "modal.holdingDays": "보유 일수",
    "modal.lastUpdate": "최근 업데이트",
    "modal.aiTradingScenario": "AI 매매 시나리오",
    "modal.buyDecision": "매수 결정",
    "modal.maxPortfolioSize": "최대 포트폴리오 규모",
    "modal.keyPriceLevels": "주요 가격대",
    "modal.sellTriggers": "매도 트리거",
    "modal.holdConditions": "보유 조건",
    "modal.portfolioContext": "포트폴리오 맥락",
    "modal.basicInfo": "기본 정보",
    "modal.buyInfo": "매수 정보",
    "modal.currentStatus": "현재 상태",
    "modal.targetStopLoss": "목표가/손절가",
    "modal.investmentPeriod": "투자 기간",
    "modal.investmentRationale": "투자 근거",
    "modal.tradingScenarios": "매매 시나리오",
    "modal.keyLevels": "주요 레벨",
    "modal.portfolioAnalysis": "포트폴리오 분석",
    "modal.valuationAnalysis": "밸류에이션 분석",
    "modal.sectorOutlook": "업종 전망",
    "modal.marketCondition": "시장 상황",
    "modal.primarySupport": "1차 지지선",
    "modal.secondarySupport": "2차 지지선",
    "modal.primaryResistance": "1차 저항선",
    "modal.secondaryResistance": "2차 저항선",
    "modal.volumeBaseline": "거래량 베이스라인",
    "modal.primarySupportShort": "1차 지지",
    "modal.secondarySupportShort": "2차 지지",
    "modal.primaryResistanceShort": "1차 저항",
    "modal.secondaryResistanceShort": "2차 저항",
    "modal.buyScore": "매수점수",

    // AI Decisions Page
    "aiDecisions.title": "AI 보유 분석",
    "aiDecisions.description": "AI가 분석한 현재 보유 종목의 매도 여부 판단",
    "aiDecisions.lastAnalysis": "최근 분석",
    "aiDecisions.sell": "매도",
    "aiDecisions.hold": "보유",
    "aiDecisions.confidence": "확신도",
    "aiDecisions.technicalTrend": "기술적 추세",
    "aiDecisions.volumeAnalysis": "거래량 분석",
    "aiDecisions.marketCondition": "시장 상황",
    "aiDecisions.timeFactor": "시간 요소",
    "aiDecisions.portfolioAdjustment": "포트폴리오 조정",
    "aiDecisions.portfolioAdjustmentNeeded": "포트폴리오 조정 필요",
    "aiDecisions.maintainStrategy": "현재 전략 유지",
    "aiDecisions.newTargetPrice": "신규 목표가",
    "aiDecisions.newStopLoss": "신규 손절가",
    "aiDecisions.urgency": "긴급도",
    "aiDecisions.reason": "사유",
    "aiDecisions.noData": "분석 데이터가 없습니다",
    "aiDecisions.pageDescription": "보유 종목에 대한 AI의 일일 판단 기록",
    "aiDecisions.totalAnalysis": "총",
    "aiDecisions.recordsCount": "건의 분석",
    "aiDecisions.totalAnalysisRecords": "총 분석 기록",
    "aiDecisions.records": "건",
    "aiDecisions.allHoldDecisions": "모두 보유 유지 판단",
    "aiDecisions.adjustmentNeeded": "조정 필요",
    "aiDecisions.portfolioRebalanceRecommended": "포트폴리오 재조정 권고",
    "aiDecisions.analyzedStocksCount": "분석 종목 수",
    "aiDecisions.stocksCount": "개",
    "aiDecisions.cumulativeBasis": "누적 종목 기준",
    "aiDecisions.analysisCount": "개 분석",
    "aiDecisions.holdMaintain": "보유 유지",
    "aiDecisions.analysisTime": "분석 시각",
    "aiDecisions.analysisPricePoint": "분석 시점 가격",
    "aiDecisions.aiJudgementBasis": "AI 판단 근거",
    "aiDecisions.analysisSummary": "분석 요약",
    "aiDecisions.marketImpact": "시장 영향",
    "aiDecisions.timeFactor2": "시간 요인",
    "aiDecisions.portfolioAdjustmentSection": "포트폴리오 조정",
    "aiDecisions.newTargetPriceHistory": "신규 목표가 이력",
    "aiDecisions.newStopLossHistory": "신규 손절가 이력",
    "aiDecisions.noAnalysisDataYet": "아직 AI 보유 분석 내역이 없습니다.",

    // Trading History Page
    "trading.title": "거래 내역",
    "trading.description": "매매 완료 종목 분석 및 AI 시나리오 비교",
    "trading.totalTrades": "총 거래",
    "trading.totalProfit": "총 손익",
    "trading.avgProfit": "평균 수익률",
    "trading.avgHoldingDays": "평균 보유",
    "trading.avgHoldingDaysShort": "평균 보유일",
    "trading.sellDate": "매도일",
    "trading.buyDate": "매수일",
    "trading.buyPrice": "매수가",
    "trading.sellPrice": "매도가",
    "trading.profitRate": "수익률",
    "trading.holdingDays": "보유일",
    "trading.holdingPeriod": "보유기간",
    "trading.filters": "필터",
    "trading.all": "전체",
    "trading.profit": "수익",
    "trading.loss": "손실",
    "trading.scenario": "시나리오",
    "trading.noData": "아직 거래 내역이 없습니다.",
    "trading.times": "회",
    "trading.winRate": "승률",
    "trading.detailedHistory": "거래 상세 내역",
    "trading.aiTargetPrice": "AI 목표가",
    "trading.targetAchievementRate": "목표 달성률",
    "trading.aiInvestmentRationale": "AI 투자 근거",
    "trading.aiScenarioDetails": "AI 매매 시나리오 상세",
    "trading.pastMarketCondition": "당시 시장 상황",
    "trading.tradeCount": "건 거래",
    "trading.completedTrades": "매매 완료 건수",
    "trading.winningTradeRatio": "수익 거래 비율",
    "trading.avgPerformancePerTrade": "거래당 평균 성과",
    "trading.daysFromBuyToSell": "매수 후 매도까지",
    "trading.bestTrade": "최고 수익 거래",
    "trading.worstTrade": "최저 수익 거래",
    "trading.sectorPerformanceTop3": "섹터별 수익률 TOP 3",
    "trading.periodPerformance": "투자기간별 성과",
    "trading.daysHeld": "일 보유",

    // Watchlist Page
    "watchlist.title": "관심 종목",
    "watchlist.description": "AI가 분석한 투자 후보 종목 (최근 1개월)",
    "watchlist.totalStocks": "전체 종목",
    "watchlist.stocksCount": "개",
    "watchlist.highestScore": "최고 점수",
    "watchlist.avgScore": "평균 점수",
    "watchlist.recentWeek": "최근 7일",
    "watchlist.scoreUnit": "점",
    "watchlist.entry": "진입",
    "watchlist.watch": "관망",
    "watchlist.reason": "사유",
    "watchlist.analyzedDate": "분석일",
    "watchlist.buyScore": "매수 점수",
    "watchlist.currentPrice": "현재가",
    "watchlist.targetPrice": "목표가",
    "watchlist.stopLoss": "손절가",
    "watchlist.tradingRationale": "매매 근거",
    "watchlist.noData": "아직 관심 종목이 없습니다.",
    "watchlist.mostPromising": "가장 유망한 종목",
    "watchlist.outOf10": "10점 만점 기준",
    "watchlist.recentlyAnalyzed": "최근 분석 종목",
    "watchlist.sectorDistributionTop3": "섹터별 분포 TOP 3",
    "watchlist.analyses": "개 분석",
    "watchlist.aiAnalysisDetails": "AI 분석 상세",
    "watchlist.copyToClipboard": "클립보드 복사",
    "watchlist.lastMonthAnalysis": "최근 1개월 분석",
    "watchlist.decision": "결정",
    "watchlist.stocksUnit": "개 종목",

    // Footer
    "footer.description": "AI 기반 주식 분석 및 매매 시스템",
    "footer.openSource": "완전 오픈소스 무료 프로젝트 • MIT License",
    "footer.features": "주요 기능",
    "footer.feature1": "12개 AI 에이전트 협업 분석",
    "footer.feature2": "급등주 자동 포착 & 리포트",
    "footer.feature3": "매매 시뮬레이션 & 자동매매",
    "footer.feature4": "실시간 성과 대시보드",
    "footer.links": "바로가기",
    "footer.sourceCode": "소스코드 & 이슈 관리",
    "footer.telegramDesc": "급등주 & 분석 리포트",
    "footer.stars": "10주 만에 250+ Stars 달성",
    "footer.disclaimer": "⚠️ 본 시스템에서 제공하는 분석 정보는 투자 참고용이며, 투자 권유를 목적으로 하지 않습니다. 모든 투자 결정과 그에 따른 손익은 투자자 본인의 책임입니다.",
  },
  en: {
    // Header
    "header.season": "Season 2",
    "header.openSource": "Open Source",
    "header.tooltip.openSource": "AI-powered Stock Analysis & Trading System • MIT License",
    "header.startDate": "Start: 2025.09.29",
    "header.updated": "Updated",
    "header.realtimeUpdate": "Real-time Update",
    "header.dashboard": "Dashboard",
    "header.aiDecisions": "AI Holdings",
    "header.trading": "Trades",
    "header.watchlist": "Watchlist",
    "header.tooltip.github": "GitHub Repository",
    "header.tooltip.telegram": "Telegram Channel",
    "header.tooltip.theme": "Toggle Theme",

    // Loading
    "loading.text": "Loading data...",

    // Tables
    "table.realPortfolio": "Real Trading Portfolio",
    "table.simulator": "Prism Simulator",
    "table.stock": "Stock",
    "table.stockName": "Stock Name",
    "table.sector": "Sector",
    "table.quantity": "Qty",
    "table.avgPrice": "Avg Price",
    "table.currentPrice": "Current",
    "table.buyPrice": "Buy Price",
    "table.targetPrice": "Target",
    "table.stopLoss": "Stop Loss",
    "table.profitRate": "Return",
    "table.profitAmount": "P&L",
    "table.totalValue": "Value",
    "table.holdingDays": "Days",
    "table.period": "Period",
    "table.weight": "Weight",
    "table.unknown": "Unknown",

    // Metrics Cards - Real Trading
    "metrics.realTrading": "Real Trading (Season 2)",
    "metrics.realTotalAssets": "Real Total Assets",
    "metrics.realHoldingsProfit": "Real Holdings P&L",
    "metrics.realProfitDist": "Real Profit Distribution",
    "metrics.startAmount": "Start Amount",
    "metrics.deposit": "Cash",
    "metrics.stocks": " stocks",
    "metrics.assetsDesc": "Holdings + Cash",
    "metrics.holdingsProfitDesc": "Current holdings P&L",
    "metrics.excludeRealized": "Unrealized only",
    "metrics.profitDistDesc": "Profit/Loss breakdown",
    "metrics.fullyInvested": "Fully invested",
    "metrics.wins": "W",
    "metrics.losses": "L",
    "metrics.breakEven": "Even",
    "metrics.totalStocks": "Total",
    "metrics.winRate": "Win Rate",

    // Metrics Cards - Simulator
    "metrics.simulator": "Prism Simulator",
    "metrics.simSoldProfit": "Sim Sold Total Return",
    "metrics.simAvgHoldingDays": "Sim Avg Holding Days",
    "metrics.simCurrentProfit": "Sim Current Holdings Return",
    "metrics.waitingSell": "Awaiting sale",
    "metrics.onlyHolding": "Only holdings exist",
    "metrics.updateOnSell": "Updates on sale",
    "metrics.soldProfitDesc": "Total return from sold stocks",
    "metrics.sold": "sold",
    "metrics.soldBasis": " sold basis",
    "metrics.needStrategy": "Review strategy",
    "metrics.avgHoldingDesc": "Avg days until sale",
    "metrics.holding": "holding",
    "metrics.avgProfit": "Avg",
    "metrics.slotUsage": "Slot usage",
    "metrics.currentProfitDesc": "Total return from current holdings",
    "metrics.started": "Started",
    "metrics.elapsed": "d elapsed",

    // Operating Costs
    "costs.title": "Project Operating Costs Transparency",
    "costs.description": "Disclosing last month's costs for sustainable open-source operations",
    "costs.serverHosting": "Server Hosting",
    "costs.basis": "as of",
    "costs.perMonth": "/ mo",
    "costs.year": "",
    "costs.month": "",
    "costs.helpQuestion": "Has this project helped you?",
    "costs.sponsorDesc": "Support sustainable development via GitHub Sponsor",
    "costs.becomeSponsor": "Become a Sponsor",

    // Badges
    "badge.realTrading": "Real Trading",
    "badge.aiSimulation": "AI Simulation",
    "badge.season2": "Season 2",
    "badge.koreanInvestment": "Korea Investment & Securities",

    // Date/Time
    "date.year": "-",
    "date.month": "-",
    "date.day": "",

    // Common
    "common.won": "KRW",
    "common.krw": "₩",
    "common.percent": "%",
    "common.days": "d",
    "common.trades": "trades",
    "common.shares": " shares",
    "common.other": "Others",
    "common.unclassified": "Unclassified",
    "metrics.totalReturn": "Total Return",
    "metrics.avgReturn": "Avg Return",
    "metrics.avgHoldingDays": "Avg Days",
    "metrics.totalTrades": "Total Trades",

    // Charts
    "chart.prismReturn": "Prism Simulator (Realized)",
    "chart.returnComparisonKospi": "Return Comparison (KOSPI)",
    "chart.returnComparisonKosdaq": "Return Comparison (KOSDAQ)",

    // Stock Detail Modal
    "modal.stockDetail": "Stock Details",
    "modal.close": "Close",
    "modal.currentPrice": "Current Price",
    "modal.profitRate": "Return",
    "modal.holdingInfo": "Holding Info",
    "modal.holdingQuantity": "Quantity",
    "modal.avgBuyPrice": "Avg Buy Price",
    "modal.evaluationAmount": "Valuation",
    "modal.evaluationPL": "P&L",
    "modal.portfolioWeight": "Portfolio Weight",
    "modal.tradingInfo": "Trading Info",
    "modal.buyDate": "Buy Date",
    "modal.buyPrice": "Buy Price",
    "modal.targetPrice": "Target",
    "modal.stopLossPrice": "Stop Loss",
    "modal.holdingDays": "Days Held",
    "modal.lastUpdate": "Last Update",
    "modal.aiTradingScenario": "AI Trading Scenario",
    "modal.buyDecision": "Buy Decision",
    "modal.maxPortfolioSize": "Max Portfolio Size",
    "modal.keyPriceLevels": "Key Price Levels",
    "modal.sellTriggers": "Sell Triggers",
    "modal.holdConditions": "Hold Conditions",
    "modal.portfolioContext": "Portfolio Context",
    "modal.basicInfo": "Basic Info",
    "modal.buyInfo": "Buy Info",
    "modal.currentStatus": "Current Status",
    "modal.targetStopLoss": "Target/Stop Loss",
    "modal.investmentPeriod": "Investment Period",
    "modal.investmentRationale": "Investment Rationale",
    "modal.tradingScenarios": "Trading Scenarios",
    "modal.keyLevels": "Key Levels",
    "modal.portfolioAnalysis": "Portfolio Analysis",
    "modal.valuationAnalysis": "Valuation Analysis",
    "modal.sectorOutlook": "Sector Outlook",
    "modal.marketCondition": "Market Condition",
    "modal.primarySupport": "Primary Support",
    "modal.secondarySupport": "Secondary Support",
    "modal.primaryResistance": "Primary Resistance",
    "modal.secondaryResistance": "Secondary Resistance",
    "modal.volumeBaseline": "Volume Baseline",
    "modal.primarySupportShort": "1st Support",
    "modal.secondarySupportShort": "2nd Support",
    "modal.primaryResistanceShort": "1st Resistance",
    "modal.secondaryResistanceShort": "2nd Resistance",
    "modal.buyScore": "Buy Score",

    // AI Decisions Page
    "aiDecisions.title": "AI Holdings Analysis",
    "aiDecisions.description": "AI analysis of current holdings for sell/hold decisions",
    "aiDecisions.lastAnalysis": "Last Analysis",
    "aiDecisions.sell": "Sell",
    "aiDecisions.hold": "Hold",
    "aiDecisions.confidence": "Confidence",
    "aiDecisions.technicalTrend": "Technical Trend",
    "aiDecisions.volumeAnalysis": "Volume Analysis",
    "aiDecisions.marketCondition": "Market Condition",
    "aiDecisions.timeFactor": "Time Factor",
    "aiDecisions.portfolioAdjustment": "Portfolio Adjustment",
    "aiDecisions.portfolioAdjustmentNeeded": "Portfolio Adjustment Needed",
    "aiDecisions.maintainStrategy": "Maintain Current Strategy",
    "aiDecisions.newTargetPrice": "New Target Price",
    "aiDecisions.newStopLoss": "New Stop Loss",
    "aiDecisions.urgency": "Urgency",
    "aiDecisions.reason": "Reason",
    "aiDecisions.noData": "No analysis data available",
    "aiDecisions.pageDescription": "Daily AI analysis records for held stocks",
    "aiDecisions.totalAnalysis": "Total",
    "aiDecisions.recordsCount": " analyses",
    "aiDecisions.totalAnalysisRecords": "Total Analysis Records",
    "aiDecisions.records": " records",
    "aiDecisions.allHoldDecisions": "All hold decisions",
    "aiDecisions.adjustmentNeeded": "Adjustment needed",
    "aiDecisions.portfolioRebalanceRecommended": "Portfolio rebalance recommended",
    "aiDecisions.analyzedStocksCount": "Analyzed Stocks Count",
    "aiDecisions.stocksCount": " stocks",
    "aiDecisions.cumulativeBasis": "Cumulative basis",
    "aiDecisions.analysisCount": " analyses",
    "aiDecisions.holdMaintain": "Hold Maintain",
    "aiDecisions.analysisTime": "Analysis time",
    "aiDecisions.analysisPricePoint": "Analysis price point",
    "aiDecisions.aiJudgementBasis": "AI Judgement Basis",
    "aiDecisions.analysisSummary": "Analysis Summary",
    "aiDecisions.marketImpact": "Market Impact",
    "aiDecisions.timeFactor2": "Time Factor",
    "aiDecisions.portfolioAdjustmentSection": "Portfolio Adjustment",
    "aiDecisions.newTargetPriceHistory": "New Target Price History",
    "aiDecisions.newStopLossHistory": "New Stop Loss History",
    "aiDecisions.noAnalysisDataYet": "No AI holding analysis data yet.",

    // Trading History Page
    "trading.title": "Trading History",
    "trading.description": "Completed trade analysis & AI scenario comparison",
    "trading.totalTrades": "Total Trades",
    "trading.totalProfit": "Total P&L",
    "trading.avgProfit": "Avg Return",
    "trading.avgHoldingDays": "Avg Holding",
    "trading.avgHoldingDaysShort": "Avg Days",
    "trading.sellDate": "Sell Date",
    "trading.buyDate": "Buy Date",
    "trading.buyPrice": "Buy Price",
    "trading.sellPrice": "Sell Price",
    "trading.profitRate": "Return",
    "trading.holdingDays": "Days",
    "trading.holdingPeriod": "Holding Period",
    "trading.filters": "Filters",
    "trading.all": "All",
    "trading.profit": "Profit",
    "trading.loss": "Loss",
    "trading.scenario": "Scenario",
    "trading.noData": "No trading history yet.",
    "trading.times": " trades",
    "trading.winRate": "Win Rate",
    "trading.detailedHistory": "Detailed History",
    "trading.aiTargetPrice": "AI Target",
    "trading.targetAchievementRate": "Target Achievement",
    "trading.aiInvestmentRationale": "AI Investment Rationale",
    "trading.aiScenarioDetails": "AI Trading Scenario Details",
    "trading.pastMarketCondition": "Market Condition at Time",
    "trading.tradeCount": " trades",
    "trading.completedTrades": "Completed trades",
    "trading.winningTradeRatio": "Winning trade ratio",
    "trading.avgPerformancePerTrade": "Avg performance per trade",
    "trading.daysFromBuyToSell": "Days from buy to sell",
    "trading.bestTrade": "Best Trade",
    "trading.worstTrade": "Worst Trade",
    "trading.sectorPerformanceTop3": "Sector Performance TOP 3",
    "trading.periodPerformance": "Period Performance",
    "trading.daysHeld": " days held",

    // Watchlist Page
    "watchlist.title": "Watchlist",
    "watchlist.description": "AI-analyzed investment candidates (Last 1 month)",
    "watchlist.totalStocks": "Total Stocks",
    "watchlist.stocksCount": " stocks",
    "watchlist.highestScore": "Highest Score",
    "watchlist.avgScore": "Avg Score",
    "watchlist.recentWeek": "Last 7 days",
    "watchlist.scoreUnit": " pts",
    "watchlist.entry": "Entry",
    "watchlist.watch": "Watch",
    "watchlist.reason": "Reason",
    "watchlist.analyzedDate": "Analyzed",
    "watchlist.buyScore": "Buy Score",
    "watchlist.currentPrice": "Current",
    "watchlist.targetPrice": "Target",
    "watchlist.stopLoss": "Stop Loss",
    "watchlist.tradingRationale": "Trading Rationale",
    "watchlist.noData": "No watchlist items yet.",
    "watchlist.mostPromising": "Most promising stock",
    "watchlist.outOf10": "Out of 10",
    "watchlist.recentlyAnalyzed": "Recently analyzed",
    "watchlist.sectorDistributionTop3": "Sector Distribution TOP 3",
    "watchlist.analyses": " analyses",
    "watchlist.aiAnalysisDetails": "AI Analysis Details",
    "watchlist.copyToClipboard": "Copy to Clipboard",
    "watchlist.lastMonthAnalysis": "Last month analysis",
    "watchlist.decision": "Decision",
    "watchlist.stocksUnit": " stocks",

    // Footer
    "footer.description": "AI-powered Stock Analysis & Trading System",
    "footer.openSource": "Fully Open Source & Free • MIT License",
    "footer.features": "Key Features",
    "footer.feature1": "12 AI Agents Collaborative Analysis",
    "footer.feature2": "Automated Surge Stock Detection & Reports",
    "footer.feature3": "Trading Simulation & Auto Trading",
    "footer.feature4": "Real-time Performance Dashboard",
    "footer.links": "Quick Links",
    "footer.sourceCode": "Source Code & Issues",
    "footer.telegramDesc": "Surge Stocks & Analysis Reports",
    "footer.stars": "250+ Stars in 10 weeks",
    "footer.disclaimer": "⚠️ The analysis information provided by this system is for reference only and is not intended as investment advice. All investment decisions and resulting profits/losses are the sole responsibility of the investor.",
  },
}

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguageState] = useState<Language>("ko")

  // Load language from localStorage on mount
  useEffect(() => {
    const stored = localStorage.getItem("language") as Language
    if (stored === "ko" || stored === "en") {
      setLanguageState(stored)
    }
  }, [])

  // Save language to localStorage when it changes
  const setLanguage = (lang: Language) => {
    setLanguageState(lang)
    localStorage.setItem("language", lang)
  }

  // Translation function
  const t = (key: string): string => {
    return translations[language][key] || key
  }

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  )
}

export function useLanguage() {
  const context = useContext(LanguageContext)
  if (context === undefined) {
    throw new Error("useLanguage must be used within a LanguageProvider")
  }
  return context
}
