#!/usr/bin/env python3
"""
YouTube Cookie Generator using Playwright

헤드리스 서버에서 Playwright를 이용해 YouTube 쿠키를 생성합니다.
로그인 없이도 봇 탐지를 우회하기 위한 기본 쿠키를 생성할 수 있습니다.
"""

import asyncio
import logging
from pathlib import Path
from datetime import datetime
from typing import Optional

logger = logging.getLogger(__name__)


async def generate_youtube_cookies(
    output_path: Optional[Path] = None,
    headless: bool = True
) -> Path:
    """
    Playwright로 YouTube에 접속하여 쿠키를 Netscape 형식으로 저장합니다.
    
    Args:
        output_path: 쿠키 파일 저장 경로 (기본: youtube_cookies.txt)
        headless: 헤드리스 모드 여부
        
    Returns:
        생성된 쿠키 파일 경로
    """
    from playwright.async_api import async_playwright
    
    if output_path is None:
        output_path = Path(__file__).parent.parent / "youtube_cookies.txt"
    
    logger.info(f"Generating YouTube cookies to: {output_path}")
    
    async with async_playwright() as p:
        # Chromium 브라우저 실행 (실제 브라우저처럼 보이도록 설정)
        browser = await p.chromium.launch(
            headless=headless,
            args=[
                '--disable-blink-features=AutomationControlled',
                '--no-sandbox',
                '--disable-dev-shm-usage',
            ]
        )
        
        # 실제 사용자처럼 보이는 컨텍스트 생성
        context = await browser.new_context(
            viewport={'width': 1920, 'height': 1080},
            user_agent='Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36',
            locale='ko-KR',
            timezone_id='Asia/Seoul',
        )
        
        page = await context.new_page()
        
        # YouTube 메인 페이지 방문
        logger.info("Visiting YouTube...")
        await page.goto('https://www.youtube.com', wait_until='networkidle')
        
        # 쿠키 동의 버튼 처리 (있는 경우)
        try:
            accept_button = page.locator('button:has-text("Accept all")')
            if await accept_button.count() > 0:
                await accept_button.click()
                logger.info("Accepted cookie consent")
                await page.wait_for_timeout(2000)
        except Exception:
            pass
        
        # 잠시 대기 (쿠키가 설정되도록)
        await page.wait_for_timeout(3000)
        
        # 영상 페이지도 방문해서 추가 쿠키 획득
        logger.info("Visiting a video page to get more cookies...")
        try:
            # 아무 영상이나 클릭하거나 직접 방문
            await page.goto('https://www.youtube.com/watch?v=dQw4w9WgXcQ', wait_until='networkidle')
            await page.wait_for_timeout(3000)
        except Exception as e:
            logger.warning(f"Could not visit video page: {e}")
        
        # 쿠키 추출
        cookies = await context.cookies()
        logger.info(f"Extracted {len(cookies)} cookies")
        
        # Netscape 쿠키 형식으로 변환
        netscape_cookies = convert_to_netscape_format(cookies)
        
        # 파일로 저장
        with open(output_path, 'w', encoding='utf-8') as f:
            f.write(netscape_cookies)
        
        logger.info(f"Cookies saved to: {output_path}")
        
        await browser.close()
        
    return output_path


def convert_to_netscape_format(cookies: list) -> str:
    """
    Playwright 쿠키를 Netscape 쿠키 형식으로 변환합니다.
    
    Netscape 형식:
    # Netscape HTTP Cookie File
    domain	flag	path	secure	expiration	name	value
    """
    lines = ["# Netscape HTTP Cookie File", "# Generated by youtube_cookie_generator.py", ""]
    
    for cookie in cookies:
        domain = cookie.get('domain', '')
        # 도메인이 .으로 시작하면 하위 도메인에도 적용
        flag = "TRUE" if domain.startswith('.') else "FALSE"
        path = cookie.get('path', '/')
        secure = "TRUE" if cookie.get('secure', False) else "FALSE"
        # expires가 없으면 세션 쿠키 (0으로 설정)
        expiration = str(int(cookie.get('expires', 0)))
        name = cookie.get('name', '')
        value = cookie.get('value', '')
        
        line = f"{domain}\t{flag}\t{path}\t{secure}\t{expiration}\t{name}\t{value}"
        lines.append(line)
    
    return '\n'.join(lines)


async def refresh_cookies_if_needed(
    cookies_path: Path,
    max_age_hours: int = 24
) -> Path:
    """
    쿠키 파일이 오래되었거나 없으면 새로 생성합니다.
    
    Args:
        cookies_path: 쿠키 파일 경로
        max_age_hours: 최대 허용 시간 (기본 24시간)
        
    Returns:
        쿠키 파일 경로
    """
    should_refresh = False
    
    if not cookies_path.exists():
        logger.info("Cookies file not found, generating new one...")
        should_refresh = True
    else:
        # 파일 수정 시간 확인
        mtime = datetime.fromtimestamp(cookies_path.stat().st_mtime)
        age_hours = (datetime.now() - mtime).total_seconds() / 3600
        
        if age_hours > max_age_hours:
            logger.info(f"Cookies file is {age_hours:.1f} hours old, refreshing...")
            should_refresh = True
        else:
            logger.info(f"Cookies file is {age_hours:.1f} hours old, still valid")
    
    if should_refresh:
        return await generate_youtube_cookies(cookies_path)
    
    return cookies_path


# CLI 지원
if __name__ == "__main__":
    import argparse
    
    logging.basicConfig(
        level=logging.INFO,
        format='%(asctime)s - %(name)s - %(levelname)s - %(message)s'
    )
    
    parser = argparse.ArgumentParser(description="Generate YouTube cookies using Playwright")
    parser.add_argument('--output', '-o', type=str, help='Output cookie file path')
    parser.add_argument('--headed', action='store_true', help='Run in headed mode (show browser)')
    args = parser.parse_args()
    
    output_path = Path(args.output) if args.output else None
    
    asyncio.run(generate_youtube_cookies(
        output_path=output_path,
        headless=not args.headed
    ))
    
    print(f"✅ Cookies generated successfully!")
